// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5EHsd2u1Bj0E_nXKCYv75EFCTwzPkZ8Y',
    appId: '1:590610330563:web:45b5c6e72ccf192571c376',
    messagingSenderId: '590610330563',
    projectId: 'test-login-e0c6c',
    authDomain: 'test-login-e0c6c.firebaseapp.com',
    storageBucket: 'test-login-e0c6c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmiM26u1vX6vHzp1E6Qv6o_YvIAJT27k8',
    appId: '1:590610330563:android:d006c376bb342b1f71c376',
    messagingSenderId: '590610330563',
    projectId: 'test-login-e0c6c',
    storageBucket: 'test-login-e0c6c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5EHsd2u1Bj0E_nXKCYv75EFCTwzPkZ8Y',
    appId: '1:590610330563:web:1d7c9c915ef3d65071c376',
    messagingSenderId: '590610330563',
    projectId: 'test-login-e0c6c',
    authDomain: 'test-login-e0c6c.firebaseapp.com',
    storageBucket: 'test-login-e0c6c.firebasestorage.app',
  );
}
